images:
    # TODO(mmiranda96): update to cos-109-lts once COS beta promotes to stable
  cos-dev:
    image_family: cos-beta
    project: cos-cloud
    metadata: "user-data</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/init.yaml,cni-template</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/cni.template,containerd-config</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/config-systemd.toml"
