presubmits:
  kubernetes-sigs/gcp-filestore-csi-driver:
  - name: pull-gcp-filestore-csi-driver-e2e
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=60" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run_e2e.sh"
        env:
        - name: ZONE
          value: us-central1-c
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
  - name: pull-gcp-filestore-csi-driver-sanity
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run_sanity.sh"
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
  - name: pull-gcp-filestore-csi-driver-unit
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run_unit.sh"
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
  - name: pull-gcp-filestore-csi-driver-verify
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10"
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "hack/verify_all.sh"
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
  - name: pull-gcp-filestore-csi-driver-kubernetes-integration
    cluster: k8s-infra-prow-build
    always_run: false
    run_if_changed: '^(pkg\/|cmd\/|test\/|hack\/|vendor\/)'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=180" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-k8s-integration.sh"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
