presubmits:
  kubernetes-sigs/gcp-compute-persistent-disk-csi-driver:
  - name: pull-gcp-compute-persistent-disk-csi-driver-e2e
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=30" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-e2e.sh"
        env:
        - name: ZONE
          value: us-central1-c
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
    annotations:
      testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
      testgrid-tab-name: presubmit-gcp-compute-persistent-disk-csi-driver-e2e
      description: Kubernetes e2e tests for Kubernetes Master branch and Driver latest build
  - name: pull-gcp-compute-persistent-disk-csi-driver-sanity
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-sanity.sh"
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
    annotations:
      testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
      testgrid-tab-name: presubmit-gcp-compute-persistent-disk-csi-driver-sanity
      description: Kubernetes sanity tests for Kubernetes Master branch and Driver latest build
  - name: pull-gcp-compute-persistent-disk-csi-driver-unit
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-unit.sh"
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
    annotations:
      testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
      testgrid-tab-name: presubmit-gcp-compute-persistent-disk-csi-driver-unit
      description: Kubernetes unit tests for Kubernetes Master branch and Driver latest build
  - name: pull-gcp-compute-persistent-disk-csi-driver-verify
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "hack/verify-all.sh"
        # docker-in-docker needs privileged mode
        # hack/verify-all.sh runs docker to validate the built docker images
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
    annotations:
      testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
      testgrid-tab-name: presubmit-gcp-compute-persistent-disk-csi-driver-verify
      description: Kubernetes verify tests for Kubernetes Master branch and Driver latest build
  - name: pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration
    cluster: k8s-infra-prow-build
    always_run: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=90" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-k8s-integration.sh"
        env:
        - name: GCE_PD_OVERLAY_NAME
          value: "dev"
        - name: GCE_PD_DO_DRIVER_BUILD
          value: "true"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 2
            memory: "6Gi"
          requests:
            cpu: 2
            memory: "6Gi"
    annotations:
      testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
      testgrid-tab-name: presubmit-gcp-compute-persistent-disk-csi-driver-kubernetes-integration
      description: Kubernetes Integration tests for Kubernetes Master branch and Driver latest build
