---
gitHubLogin: "kyma-bot"
gitHubToken: "/etc/github-token/oauth"
gitName: "Kyma Bot"
gitEmail: "kyma.bot@sap.com"
selfAssign: true # Commenting `/cc`, so that autobump PR is not assigned to anyone
skipPullRequest: false
gitHubOrg: "kyma-project"
gitHubRepo: "k8s-prow"
remoteName: "test-infra"
upstreamURLBase: "https://raw.githubusercontent.com/kubernetes/test-infra/master"
includedConfigPaths:
  - "."
targetVersion: "latest"
prefixes:
  - name: "testimages"
    prefix: "europe-docker.pkg.dev/kyma-project/prod/testimages/"
    refConfigFile: "config/prow/cluster/deck_deployment.yaml"
    repo: "https://github.com/kyma-project/test-infra"
    summarise: true
    consistentImages: true